### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-3-sintesis-IrvingFernand0#2]
[Sintesis_GestionDeProyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-IrvingFernand0/files/12516416/Sintesis_GestionDeProyectos.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
